library(tibble)


livestock_weights <- structure(list(survey_value = c("fish",
                          "pigs",
                          "chicken",
                          "cattle",
                          "ducks",
                          "goats",
                          "donkeys_horses",
                          "rabbits",
                          "crocodile",
                          "otherpoultry",
                          "geese",
                          "buffalo",
                          "guinea_pigs",
                          "doves",
                          "camel",
                          "llama",
                          "alpaca",
                          "sheep"),
               conversion = c(1,
                             150,
                             1,
                             250,
                             1,
                             25,
                             250,
                             1,
                             55,
                             1,
                             2,
                             250,
                             1,
                             1,
                             250,
                             250,
                             250,
                             25)),
          row.names = c(NA, -18L),
          class = c("tbl_df", "tbl", "data.frame"))

usethis::use_data(livestock_weights, overwrite = TRUE)

