---
title: "RHoMIS Process Pipeline"
author: "Léo Gorman"
date: "21/06/2021"
output: html_document
---

## Setup
```{r setup, echo=T}
library(rhomis)
library(knitr)

# Loading environemnt variables from .env file
readRenviron(".env")

central_url <- "https://central.rhomis.cgiar.org"
# Accessing the environemnt variables
central_email <- Sys.getenv("RHOMIS_CENTRAL_EMAIL")
central_password <- Sys.getenv("RHOMIS_CENTRAL_PASSWORD")

# The name of the project we are interested in
project_name <- "Leo Test 1"
```

## Exploring ODK central
```{r central_explore, message=FALSE, warning=FALSE}
# Get data on the different central users
users <- get_users(central_url,
                   central_email,
                   central_password)
kable(users)

# Get a list of the different central projects
projects <-get_projects(central_url,
                        central_email,
                        central_password)
kable(projects)

#' Identify which project ID matches the project
#' name we are interested in
projectID <- projects$id[projects$name==project_name]

forms <- get_forms(central_url,
                   central_email,
                   central_password,
                   projectID)
kable(forms)

# We are interested in the first form from this project
formID <- forms$xmlFormId[1]

# Get data on the
submissions_list <- get_submissions_list(central_url,
                                         central_email,
                                         central_password,
                                         projectID,
                                         formID)
kable(submissions_list)

rhomis_data <- get_submission_data(central_url,
                                   central_email,
                                   central_password,
                                   projectID,
                                   formID )
kable(rhomis_data) 
```

