# Copyright (C) 2022 Léo Gorman
#
# This file is part of rhomis-data-app.
#
# rhomis-data-app is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rhomis-data-app is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rhomis-data-app.  If not, see <http://www.gnu.org/licenses/>.

name: Deploy Bookdown docs
on:
  push:
    branches:
      - dev

jobs:
  build-book:
    name: Render-Book
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1
    - name: Install rmarkdown
      run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'

    - name: Render Book
      run: Rscript -e 'bookdown::render_book("./book")'
    - uses: actions/upload-artifact@v1
      with:
        name: _book
        path: ./book/_book/

  deploy-book:
    name: Deploy-Book
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
         # Artifact name
          name: _book # optional
         # Destination path
          path: _book # optional
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
            EMAIL: ${{ secrets.GITHUBEMAIL }}               # must be a verified email
            GH_TOKEN: ${{ secrets.PUBLISHBOOKDOWN }} # https://github.com/settings/tokens
            BUILD_DIR: _book/                     # "_site/" by default
